services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
      - ./testing/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  pismo-app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb
volumes:
  mongo_data:
