version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  pismo-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017/?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy